### ISSUE TITLE
About the onedrive link of ScanNet Feature.

### ISSUE THREAD

**Issue by zhaihongjia** [yanmin-wu/OpenGaussian#1]
Hello, I can not download your preprocessed ScanNet data. Maybe the onedrive link is wrong. Can you share the data to me?

**Comment by yanmin-wu** [comment]
Hi, I just checked that the link is correct and asked someone else to try it and it worked. Could you please check again? Let me know if there are still any problems.

**Comment by zhaihongjia** [comment]
Thanks for your reply. I fix the bug in my proxy.

**Comment by jameelhassan** [comment]
@zhaihongjia were you able to fix it and dowload it using the OneDrive link? It does not seem to work for me either. 

<img width="1032" height="493" alt="Image" src="https://github.com/user-attachments/assets/2c8e282a-05ff-46ae-b346-c8b1d5d6161c" />
