### ISSUE TITLE
Data unavailable

### ISSUE THREAD

**Issue by Jumpat** [yanmin-wu/OpenGaussian#4]
Hello. Thanks for your open source! 

I found that the data you provided (the [OneDrive](https://onedrive.live.com/?authkey=%21AIgsXZy3gl%5FuKmM&id=744D3E86422BE3C9%2139815&cid=744D3E86422BE3C9) links) is unavailable. And network proxy seems useless. Can you provide a gdrive or Baidu cloud version?

**Comment by Jumpat** [comment]
It seems okay now.

**Comment by fy99925** [comment]
Now it doesn't seem to be available again.
